### ISSUE TITLE
offsets?

### ISSUE THREAD

**Issue by lizzard-winner** [br0k3/urban-terror-hack#1]
Hey how did you get the cg_entitys offsets? i tryd looking for cg_init but couldn't find it.

**Comment by br0k3** [comment]
Hey Jonathan,
Sorry for late reply don't check my email with that github as often as others.  
Wow, the offsets it was soo long ago hah for 4.1.  But i used a tool called qvmkanker or qvmdump/objdump and grep'd for different strings.  Man, really wish I would've written down my procedure on that kind of did it on the fly using *nixcoders team's code from 4.0 and some old forum thread information.
I remember white or red being involved in the string I was searching out.
sorry couldn't be of much help now.  Also, 4.2 to my knowledge they totally changed the way the qvm memory is stored to counter CG hacks.
Anyhow, good luck!
-br0k3

Date: Sun, 22 Dec 2013 08:38:56 -0800

**Comment by lizzard-winner** [comment]
Thanks for the reply.
Yes you probably searched for "white", which doesn't work anymore now, thank you nonetheless!
